-- All columns already exist in production (all in schema.ts, app is running); no-op migration
-- Removed: factories.businessType, operationStatus, certified, avgResponseHours,
--          weekdayHours, weekendHours, businessNote; products.priceType; reviews.reply, repliedAt
